### ISSUE TITLE
can you bump madcat version to 0.3.0?

### ISSUE THREAD

**Issue by trunghung** [rjkip/grunt-mapcat#3]
thanks

**Comment by rjkip** [comment]
Hi @trunghung, I'll look into this tomorrow!

**Comment by rjkip** [comment]
Here you go @trunghung. The `maproot` option can be [configured as such](https://github.com/rjkip/grunt-mapcat/blob/ba861635fb1d68b9fc22f2a9ee2e52741a06c0f5/Gruntfile.js#L38-L44).

**Comment by trunghung** [comment]
Thanks Reiner, I have a question for you.  The generated source map from mapcat including the one you included in the expected test example appears to be bad.  Basically all the code inside the map file are unmapped so when I opened it up in either webstorm or chrome, the individual files appear empty and has no content. I was just wondering if you are aware of this issue?
